#!/bin/sh

INSTANCE_NAME="cade"
SHARE_DIR="$HOME/.local/share/cade"
USERNAME="$(id -un)"
LAUNCH_DIR="$(pwd)"

LAUNCH_YAML=$(
cat <<'EOF'
#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: false

users:
  - name: @USERNAME@
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: true
    homedir: /home/@USERNAME@

packages:
  - curl
  - exfat-fuse  # for appimages
  - git
  - gnome-keyring
  - iproute2
  - jq
  - rsync
  - socat
  - squid-openssl
  - sysstat
  - vim

snap:
  commands:
    - snap install docker
    - snap install charmcraft --classic
    - snap install rockcraft --classic --edge

write_files:
- content: |
    #!/bin/sh
    USERNAME="$(id -un)"
    [ -n "$1" ] && TYPE="$1" || TYPE="CHANNEL"
    [ -n "$2" ] && TARGET="$2" || TARGET="1.27-strict/stable"
    sudo snap remove --purge microk8s
    case "$TYPE" in
      chan*|CHAN*)
        sudo snap install microk8s --channel="$TARGET";;
      dir*|DIR*)
        cd "$TARGET"
        sudo snap ack microk8s_*.assert
        sudo snap install microk8s_*.snap
        find . -name "*.tar" | xargs -n1 sudo microk8s ctr images import --platform amd64;;
    esac
    sudo cp /etc/squid/squid-self-signed.crt /var/snap/microk8s/current/certs/
    sudo echo 'ca = "/var/snap/microk8s/current/certs/squid-self-signed.crt"' >> /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml
    sudo echo 'ca = "/var/snap/microk8s/current/certs/squid-self-signed.crt"' >> /var/snap/microk8s/current/args/certs.d/localhost\:32000/hosts.toml
    sudo cp -r /var/snap/microk8s/current/args/certs.d/localhost\:32000/ /var/snap/microk8s/current/args/certs.d/quay.io/
    sudo sed -i 's/localhost:32000/quay.io/g' /var/snap/microk8s/current/args/certs.d/quay.io/hosts.toml
    sudo cp -r /var/snap/microk8s/current/args/certs.d/localhost\:32000/ /var/snap/microk8s/current/args/certs.d/registry.k8s.io/
    sudo sed -i 's/localhost:32000/registry.k8s.io/g' /var/snap/microk8s/current/args/certs.d/registry.k8s.io/hosts.toml
    sudo snap restart microk8s
    mkdir -p "/home/$USERNAME/.kube"
    sudo chown -f -R "$USERNAME" "/home/$USERNAME/.kube"
    sudo snap alias microk8s.kubectl kubectl
    sudo microk8s.enable dns
    sudo microk8s.kubectl rollout status deployments/coredns -n kube-system -w --timeout=600s
    sudo microk8s.enable hostpath-storage
    sudo microk8s.enable ingress
    sudo microk8s.kubectl rollout status deployments/hostpath-provisioner -n kube-system -w --timeout=600s
    sudo microk8s.kubectl rollout status daemonsets/nginx-ingress-microk8s-controller -n ingress -w --timeout=600s
    sudo microk8s.enable rbac
    sudo microk8s.enable registry
    IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
    sudo microk8s.enable "metallb:$IPADDR-$IPADDR"
    sudo microk8s config > "/home/$USERNAME/.kube/config"
  path: /usr/local/bin/reset_microk8s
  permissions: '0755'
- content: |
    #!/bin/sh
    set -xe
    USERNAME="$(id -un)"
    [ -n "$1" ] && TYPE="$1" || TYPE="CHANNEL"
    [ -n "$2" ] && TARGET="$2" || TARGET="3.1"
    [ "3.0" = "$(printf "3.0\\n%s" "$TARGET" | sort -V | head -n1)" ] && oldflag="no" || oldflag="yes"
    sudo snap remove --purge juju
    rm -rf "/home/$USERNAME/.local/share/juju"
    case "$TYPE" in
      chan*|CHAN*)
        reset_microk8s
        reset_lxd
        if [ "$oldflag" = "yes" ]; then
          sudo snap install juju --classic --channel="$TARGET"
        else
          sudo snap install juju --channel="$TARGET"
        fi;;
      rev*|REV*)
        reset_microk8s
        reset_lxd
        sudo snap install juju --classic --revision="$TARGET";;
      ver*|VER*)
        reset_microk8s
        reset_lxd
        build_juju "$TARGET";;
      dir*|DIR*)
        cd "$TARGET"
        reset_microk8s DIR "$TARGET"
        reset_lxd DIR "$TARGET"
        sudo snap ack juju_*.assert
        sudo snap install juju_*.snap
    esac
    juju update-public-clouds --client
    sudo snap restart microk8s
    juju update-k8s --client microk8s
    juju bootstrap microk8s mk8s
    if [ "$oldflag" = "no" ]; then
      juju model-defaults --cloud=microk8s logging-config='<root>=WARNING;unit=DEBUG;http=TRACE'
    else
      juju model-defaults microk8s logging-config='<root>=WARNING;unit=DEBUG;http=TRACE'
    fi
    juju add-model dev
    if [ "$3" = "--with-machine" ]; then
      juju bootstrap localhost lxd
      if [ "$oldflag" = "no" ]; then
        juju model-defaults --cloud=localhost logging-config='<root>=WARNING;unit=DEBUG;http=TRACE'
      else
        juju model-defaults localhost logging-config='<root>=WARNING;unit=DEBUG;http=TRACE'
      fi
      microk8s.config | juju add-k8s mk8s --controller=lxd
      juju add-model devk8s mk8s
      juju add-model db localhost
    fi
  path: /usr/local/bin/reset_juju
  permissions: '0755'
- content: |
    #!/bin/sh
    build_dir="$(mktemp -d -p "$HOME")"
    cd "$build_dir"
    git clone --depth 1 --branch "juju-$1" https://github.com/juju/juju.git .
    sudo snap install snapcraft --classic
    snapcraft --use-lxd
    sudo snap install *.snap --dangerous
    sudo snap connect juju:config-lxd
    sudo snap connect juju:dot-aws
    sudo snap connect juju:dot-azure
    sudo snap connect juju:dot-google
    sudo snap connect juju:dot-kubernetes
    sudo snap connect juju:dot-local-share-juju
    sudo snap connect juju:dot-maas
    sudo snap connect juju:dot-openstack
    sudo snap connect juju:dot-oracle
    sudo snap connect juju:lxd lxd
    sudo snap connect juju:network
    sudo snap connect juju:network-bind
    sudo snap connect juju:peers microk8s
    sudo snap connect juju:ssh-keys
    rm -rf "$build_dir"
  path: /usr/local/bin/build_juju
  permissions: '0755'
- content: |
    #!/bin/sh
    [ -n "$1" ] && TYPE="$1" || TYPE="CHANNEL"
    [ -n "$2" ] && TARGET="$2" || TARGET="5.19/stable"
    sudo snap remove --purge lxd
    case "$TYPE" in
      chan*|CHAN*)
        sudo snap install lxd --channel="$TARGET";;
      dir*|DIR*)
        cd "$TARGET"
        sudo snap ack lxd_*.assert
        sudo snap install lxd_*.snap
    esac
    lxd init --auto
    sudo iptables -P FORWARD ACCEPT
  path: /usr/local/bin/reset_lxd
  permissions: '0755'
- content: |
    visible_hostname squid.internal

    # Example rule allowing access from your local networks.
    # Adapt to list your (internal) IP networks from where browsing
    # should be allowed
    acl localnet src 0.0.0.1-0.255.255.255  # RFC 1122 "this" network (LAN)
    acl localnet src 10.0.0.0/8             # RFC 1918 local private network (LAN)
    acl localnet src 100.64.0.0/10          # RFC 6598 shared address space (CGN)
    acl localnet src 169.254.0.0/16         # RFC 3927 link-local (directly plugged) machines
    acl localnet src 172.16.0.0/12          # RFC 1918 local private network (LAN)
    acl localnet src 192.168.0.0/16         # RFC 1918 local private network (LAN)
    acl localnet src fc00::/7               # RFC 4193 local private network range
    acl localnet src fe80::/10              # RFC 4291 link-local (directly plugged) machines

    acl SSL_ports port 443
    acl Safe_ports port 80          # http
    acl Safe_ports port 21          # ftp
    acl Safe_ports port 443         # https
    acl Safe_ports port 70          # gopher
    acl Safe_ports port 210         # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280         # http-mgmt
    acl Safe_ports port 488         # gss-http
    acl Safe_ports port 591         # filemaker
    acl Safe_ports port 777         # multiling http

    # Don't cache by default
    cache deny localnet
    acl domain_to_cache dstdomain .docker.io .snapcraft.io .docker.com .linuxcontainers.org .ubuntu.com .gcr.io .k8s.io .amazonaws.com
    cache allow domain_to_cache
    cache deny all

    # Recommended minimum Access Permission configuration:
    # Deny requests to certain unsafe ports
    http_access deny !Safe_ports

    # Deny CONNECT to other than secure SSL ports
    http_access deny CONNECT !SSL_ports

    # Only allow cachemgr access from localhost
    http_access allow localhost manager
    http_access deny manager

    # INSERT YOUR OWN RULE(S) HERE TO ALLOW ACCESS FROM YOUR CLIENTS
    include /etc/squid/conf.d/*.conf

    # Example rule allowing access from your local networks.
    # Adapt localnet in the ACL section to list your (internal) IP networks
    # from where browsing should be allowed
    #http_access allow localnet
    http_access allow localhost

    # And finally deny all other access to this proxy
    http_access deny all

    # Squid normally listens to port 3128
    http_port 3128 ssl-bump generate-host-certificates=on tls-cert=/etc/squid/squid-self-signed.pem tls-key=/etc/squid/squid-self-signed.key tls-dh=prime256v1:/etc/squid/squid-self-signed_dhparam.pem tls-default-ca=on

    # Become a TCP tunnel without decrypting proxied traffic.
    ssl_bump server-first all

    maximum_object_size 6 GB

    # Uncomment and adjust the following to add a disk cache directory.
    cache_dir ufs /var/spool/squid 32000 16 256

    # Leave coredumps in the first cache dir
    coredump_dir /var/spool/squid

    # Add any of your own refresh_pattern entries above these.
    refresh_pattern ^ftp:           1440    20%     10080
    refresh_pattern ^gopher:        1440    0%      1440
    refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
    refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
    refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
    refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
    refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
    # example pattern for deb packages
    #refresh_pattern (\.deb|\.udeb)$   129600 100% 129600
    refresh_pattern .               0       20%     4320
  path: /etc/squid/squid.conf
  permissions: '0644'
- content: |
    HTTPS_PROXY=http://squid.internal:3128
    HTTP_PROXY=http://squid.internal:3128
    NO_PROXY=10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16,.svc,.cluster.local
    https_proxy=http://squid.internal:3128
    http_proxy=http://squid.internal:3128
    no_proxy=10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16,.svc,.cluster.local
  path: /etc/environment
  permissions: '0644'

runcmd:
  - |
    # disable swap
    sysctl -w vm.swappiness=0
    echo "vm.swappiness = 0" | tee -a /etc/sysctl.conf
    swapoff -a

  - |
    # setup docker
    addgroup --system docker
    adduser @USERNAME@ docker
    snap disable docker
    snap enable docker

  - |
    # add lxd group for later
    # Follow: https://github.com/canonical/ubuntu-core-desktop-snapd/blob/master/osutil/user.go#L150
    groupadd --system lxd
    useradd --system --home-dir /nonexistent --no-create-home --shell /bin/false --no-user-group -g lxd lxd
    adduser @USERNAME@ lxd

  - |
    # add microk8s groups for later
    # Follow: https://github.com/canonical/ubuntu-core-desktop-snapd/blob/master/osutil/user.go#L150
    # 584789 should be used as uid/gid for snap_microk8s: https://github.com/snapcore/snapd/blob/master/snap/system_usernames.go#L156C24-L156C30
    groupadd --system --gid 584789 snap_microk8s
    useradd --system --home-dir /nonexistent --no-create-home --shell /bin/false --no-user-group -g snap_microk8s --uid 584789 snap_microk8s
    adduser @USERNAME@ snap_microk8s
    groupadd --system microk8s
    useradd --system --home-dir /nonexistent --no-create-home --shell /bin/false --no-user-group -g microk8s microk8s
    adduser @USERNAME@ microk8s

  - |
    # disable unnecessary services
    systemctl disable man-db.timer man-db.service --now
    systemctl disable apport.service apport-autoreport.service  --now
    systemctl disable apt-daily.service apt-daily.timer --now
    systemctl disable apt-daily-upgrade.service apt-daily-upgrade.timer --now
    systemctl disable unattended-upgrades.service --now
    systemctl disable motd-news.service motd-news.timer --now
    systemctl disable bluetooth.target --now
    systemctl disable ua-messaging.service ua-messaging.timer --now
    systemctl disable ua-timer.timer ua-timer.service --now
    systemctl disable systemd-tmpfiles-clean.timer --now

  - |
    # apt cleanup
    apt-get remove -y landscape-client landscape-common
    apt-get autoremove -y

  - |
    # install squid
    echo "127.0.0.1 squid.internal" >> /etc/hosts
    mkdir -p /var/spool/squid
    chown proxy: /var/spool/squid
    cd /etc/squid
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -extensions v3_ca -keyout squid-self-signed.key -out squid-self-signed.crt -subj "/CN=cade"
    openssl x509 -in squid-self-signed.crt -outform DER -out squid-self-signed.der
    openssl x509 -in squid-self-signed.crt -outform PEM -out squid-self-signed.pem
    openssl dhparam -outform PEM -out squid-self-signed_dhparam.pem 2048
    sudo cp /etc/squid/squid-self-signed.pem /usr/local/share/ca-certificates/squid-self-signed.crt
    update-ca-certificates
    sudo -u proxy /usr/lib/squid/security_file_certgen -c -s /var/spool/squid/ssl_db -M 4MB
    systemctl restart squid
EOF
)

if [ "$1" = "expose" ]; then
  if [ -z "$2" ]; then
    echo "You need to specify a port"
    exit 1
  fi
  cade unexpose
  mkdir -p "$SHARE_DIR"
  [ -f "$SHARE_DIR"/sshkey ] || ssh-keygen -N "" -t ed25519 -C "cade-multipass-$(date -I)" -f "$SHARE_DIR/sshkey"
  sed -i '/cade-multipass/d' "$HOME/.ssh/authorized_keys"
  cat "$SHARE_DIR/sshkey.pub" >> "$HOME/.ssh/authorized_keys"
  (
    cade_ip="$(multipass list | grep "$INSTANCE_NAME" | awk '{print $3}')"
    sudo nohup ssh -v -N -i "$SHARE_DIR/sshkey" -L "$2:127.0.0.1:$2" "$USERNAME@$cade_ip" > "$SHARE_DIR/tunnel.log" &
    echo $! > "$SHARE_DIR/expose.pid"
  ) 2>/dev/null >/dev/null
  exit
fi

if [ "$1" = "unexpose" ]; then
  if [ -f "$SHARE_DIR/expose.pid" ]; then
    sudo kill "$(cat "$SHARE_DIR/expose.pid")"
    rm "$SHARE_DIR/expose.pid"
  fi
  exit
fi

if [ "$1" = "clean" ]; then
  printf 'Are you sure (y/N)? '
  read -r answer
  if [ "$answer" != "${answer#[Yy]}" ] ;then
    if multipass list | grep -v "Deleted" | grep "^$INSTANCE_NAME " > /dev/null; then
      multipass delete "$INSTANCE_NAME"
      multipass purge
    fi
    sed -i '/cade-multipass/d' "$HOME/.ssh/authorized_keys"
    rm -rf "$SHARE_DIR"
  fi
  exit
fi

if [ "$1" = "stop" ]; then
  multipass stop "$INSTANCE_NAME"
  exit
fi

if [ -n "$1" ]; then
  cat << 'EOF'
Cade: A tool for setting up a charm development environment using Multipass.

Usage:
  cade expose <port>
  cade unexpose
  cade clean
  cade stop
  cade

Options:
  expose <port>      Expose the specified port for the Cade instance.
  unexpose           Terminate the exposed port session for the Cade instance.
  clean              Purge and remove Cade instance and its associated files, after confirmation.
  stop               Stop the Cade instance.
                     (No option) Starts or initializes the Cade instance if not already done.

Notes:
  - `cade expose` sets up an SSH tunnel from the host machine to the Cade instance on the specified port.
  - `cade unexpose` kills the SSH tunnel process for the exposed port.
  - `cade clean` offers a prompt for confirmation before deleting the instance and associated files.
  - Running `cade` with no arguments ensures that the Cade instance is running, mounts the user's home directory, and starts an interactive shell within the instance.
EOF
  exit
fi

if ! multipass list | grep -v "Deleted" | grep "^$INSTANCE_NAME " > /dev/null; then
  echo "Creating instance"
  # We're purging to remove the instance if it was deleted
  multipass purge
  # We're creating the temporary file in $HOME to be sure 
  # that multipass as a snap can read it
  launch_file="$(mktemp -p "$HOME")"
  echo "$LAUNCH_YAML" > "$launch_file"
  sed -i -e "s|@USERNAME@|${USERNAME}|g" "$launch_file"
  multipass launch -n "$INSTANCE_NAME" --cloud-init "$launch_file" --cpus 4 --memory 16G --disk 128G || true
  rm "$launch_file"
fi

multipass start "$INSTANCE_NAME" || true
multipass mount -g "$(id -g):1000" -u "$(id -u):1000" ~ "$INSTANCE_NAME" 2>/dev/null || true

# launching a shell with the correct user inside the VM to the right path
multipass exec "$INSTANCE_NAME" -- sudo -i -u "$USERNAME" "sh -c 'cd "$LAUNCH_DIR"; /bin/bash'"
